# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Facebook-API-REST-Client
version:      v0.0.3
version_from: lib/WWW/Facebook/API/REST/Client.pm
installdirs:  site
requires:
    Digest::MD5:                   0
    Moose:                         0
    Test::More:                    0
    Time::HiRes:                   0
    URI::Escape:                   0
    version:                       0
    WWW::Mechanize:                0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
